#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to store the images
# NOCACHE: set this to "--no-cache" to turn off the Docker build cache
#
# NOTE: to run this you MUST set the REGISTRY environment variable to
# your own image registry/namespace otherwise the `docker push` commands
# will fail due to an auth failure. Which means, you also need to be logged
# into that registry before you run it.

set -ex
export REGISTRY=${REGISTRY:-icr.io/codeengine}

# Clone the repository
git clone https://github.com/MohanadAAST/chatbot-aast.git

# Enter the repository directory
cd chatbot-aast

# Build the image
docker build ${NOCACHE} -t ${REGISTRY}/chatbot-aast . --platform linux/amd64

# And push it
docker push ${REGISTRY}/chatbot-aast
